backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Start Seite"
        name: "StartSeite"
        file: "content/StartSeite.md"
        fields:
          - label: "Methodik Didaktik"
            name: "methodik_didaktik"
            widget: list
            fields:
              - { label: "Headline", name: "headline", widget: "string" }
              - { label: "Test", name: "text", widget: "text" }
              - label: "Icon"
                name: "icon"
                widget: "select"
                options:
                  [
                    "fist-raised",
                    "language",
                    "compress-arrows-alt",
                    "arrows-alt",
                  ]
